name: MaxEnchants
author: Xenophilicy
version: 1.2.5
main: Xenophilicy\MaxEnchants\MaxEnchants
api: 5.0.0
description: Enable enchants up to level 32k!
commands:
  menchants:
    description: Get info on MaxEnchants
    permission: menchants.info
permissions:
  menchants.info:
    default: op
  menchants.enchant:
    default: op
